title: That (D)Transit Blog
description: News, insights, and deep dives into the world of public transit — the blog version of DTransit.
url: "https://dtransit-main.github.io"
baseurl: "/thatdtransitblog"

theme: null
markdown: kramdown
plugins:
  - jekyll-feed
paginate: 10
paginate_path: "/posts/page:num/"